name: Deploy Python project to Azure Function App

on:
  push:

env:
  AZURE_FUNCTIONAPP_NAME: '1js-hackathon-cri-ai'   # your Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'              # path to your function app project
  PYTHON_VERSION: '3.10'                           # Python version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Set up Python ${{ env.PYTHON_VERSION }}'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # Optional: run tests or lint before deploy
    # - name: 'Install dependencies for testing'
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    # - name: 'Run Tests'
    #   run: pytest

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
