name: Deploy Python project to Azure Function App

on:
  push:

env:
  AZURE_FUNCTIONAPP_NAME: '1js-hackathon-cri-ai'   # your Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'              # path to your function app project
  PYTHON_VERSION: '3.12'                           # Python version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Set up Python ${{ env.PYTHON_VERSION }}'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Install dependencies into .python_packages'
      shell: bash
      run: |
        pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Create deployment package'
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        zip -r ../app.zip .
        cd ..

    - name: 'Deploy via ZipDeploy'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: app.zip
